"use client";
import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,PieChart,Pie,Cell,Legend,AreaChart,Area,CartesianGrid} from "recharts";

export function DashboardCharts({vendorData,statusData,cashflowData}:{vendorData:any[];statusData:any[];cashflowData:any[]}){
  const router=useRouter();
  const [months,setMonths]=useState<"6"|"12"|"all">("12");
  const [showDue,setShowDue]=useState(true);
  const [showPaid,setShowPaid]=useState(true);
  const visibleCashflow=useMemo(()=>months==="all"?cashflowData:cashflowData.slice(-Number(months)),[cashflowData,months]);
  const money=(v:any)=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2});
  return <div className="grid gap-5 xl:grid-cols-2">
    <section className="mccs-card rounded-2xl p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-bold">Commitment by Vendor</h2><p className="mt-1 text-sm text-slate-500">Live commercial commitments. Click a bar to filter the dashboard by supplier.</p></div><span className="rounded-lg bg-blue-50 px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wide text-blue-700">Interactive</span></div><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={vendorData} onClick={(e:any)=>{const d=e?.activePayload?.[0]?.payload;if(d?.vendorId)router.push(`/dashboard?vendor=${encodeURIComponent(d.vendorId)}`)}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip formatter={(v:any)=>money(v)} cursor={{fill:"rgba(37,99,235,.06)"}}/><Bar dataKey="value" radius={[8,8,0,0]} fill="#2563eb" cursor="pointer"/></BarChart></ResponsiveContainer></div></section>
    <section className="mccs-card rounded-2xl p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-bold">Milestone Status</h2><p className="mt-1 text-sm text-slate-500">Current payment milestone pipeline; values update with the supplier filter.</p></div><a href="/payment-milestones" className="rounded-lg border px-3 py-2 text-xs font-bold text-blue-700 hover:bg-blue-50">Open register</a></div><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={statusData} dataKey="value" nameKey="name" innerRadius={65} outerRadius={100} paddingAngle={3}>{statusData.map((_:any,i:number)=><Cell key={i} fill={["#2563eb","#0f766e","#d97706","#7c3aed","#64748b","#dc2626"][i%6]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></div></section>
    <section className="mccs-card rounded-2xl p-6 xl:col-span-2"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-bold">Commercial Cash Flow</h2><p className="mt-1 text-sm text-slate-500">Dynamic monthly milestone due value versus actual payments.</p></div><div className="flex flex-wrap items-center gap-2"><div className="flex rounded-lg border bg-white p-1 dark:bg-slate-900">{[["6","6M"],["12","12M"],["all","All"]].map(([v,l])=><button key={v} type="button" onClick={()=>setMonths(v as any)} className={`rounded-md px-3 py-1.5 text-xs font-bold ${months===v?"bg-blue-700 text-white":"text-slate-600 hover:bg-slate-50"}`}>{l}</button>)}</div><button type="button" onClick={()=>setShowDue(x=>!x)} className={`rounded-lg border px-3 py-2 text-xs font-bold ${showDue?"border-blue-200 bg-blue-50 text-blue-700":"text-slate-400"}`}>Milestone Due</button><button type="button" onClick={()=>setShowPaid(x=>!x)} className={`rounded-lg border px-3 py-2 text-xs font-bold ${showPaid?"border-emerald-200 bg-emerald-50 text-emerald-700":"text-slate-400"}`}>Paid</button></div></div><div className="mt-5 h-80"><ResponsiveContainer width="100%" height="100%"><AreaChart data={visibleCashflow}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip formatter={(v:any)=>money(v)}/><Legend/>{showDue?<Area type="monotone" dataKey="due" name="Milestone Due" fill="#bfdbfe" stroke="#2563eb"/>:null}{showPaid?<Area type="monotone" dataKey="paid" name="Paid" fill="#bbf7d0" stroke="#16a34a"/>:null}</AreaChart></ResponsiveContainer></div></section>
  </div>
}
