import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
export const dynamic="force-dynamic";

type Hit={type:string;title:string;subtitle:string;href:string;meta?:string};
function like(q:string){return `%${q.replace(/[%_]/g,"\\$&")}%`}
export default async function SearchPage({searchParams}:{searchParams:Promise<{q?:string}>}){
 const {q=""}=await searchParams; const term=q.trim(); const s=await createClient(); if(!s)return null; const hits:Hit[]=[];
 if(term){const p=like(term);
  const [vr,pr,por,ir,pyr,dr,mr]=await Promise.all([
   s.from("vendors").select("id,vendor_code,vendor_name,legal_name,email,phone").or(`vendor_code.ilike.${p},vendor_name.ilike.${p},legal_name.ilike.${p},email.ilike.${p},phone.ilike.${p}`).eq("is_active",true).limit(25),
   s.from("projects").select("id,project_code,project_name,description").or(`project_code.ilike.${p},project_name.ilike.${p},description.ilike.${p}`).eq("is_active",true).limit(25),
   s.from("purchase_orders").select("id,po_number,pr_number,rfq_number,status,payment_terms,delivery_terms,approved_by_text").or(`po_number.ilike.${p},pr_number.ilike.${p},rfq_number.ilike.${p},status.ilike.${p},payment_terms.ilike.${p},delivery_terms.ilike.${p},approved_by_text.ilike.${p}`).eq("is_deleted",false).limit(40),
   s.from("invoices").select("id,invoice_number,status,workflow_status,verification_ref").or(`invoice_number.ilike.${p},status.ilike.${p},workflow_status.ilike.${p},verification_ref.ilike.${p}`).eq("is_deleted",false).limit(40),
   s.from("payments").select("id,payment_reference,bank_reference,payment_date,paid_amount").or(`payment_reference.ilike.${p},bank_reference.ilike.${p}`).limit(30),
   s.from("documents").select("id,document_title,document_type,file_name,revision,google_drive_web_url").or(`document_title.ilike.${p},document_type.ilike.${p},file_name.ilike.${p},revision.ilike.${p}`).limit(30),
   s.from("payment_milestones").select("id,milestone_name,status,payment_due_date").or(`milestone_name.ilike.${p},status.ilike.${p}`).limit(30),
  ]);
  (vr.data??[]).forEach((x:any)=>hits.push({type:"Vendor",title:x.vendor_name,subtitle:x.vendor_code||x.legal_name||"Vendor / Contractor",href:`/vendors/${x.id}/edit`,meta:x.email||x.phone||""}));
  (pr.data??[]).forEach((x:any)=>hits.push({type:"Project / Package",title:x.project_name,subtitle:x.project_code||"Commercial package",href:`/projects/${x.id}/edit`,meta:x.description||""}));
  (por.data??[]).forEach((x:any)=>{hits.push({type:"Purchase Order",title:x.po_number,subtitle:`Status: ${x.status||"—"}`,href:`/purchase-orders/${x.id}`,meta:[x.pr_number&&`PR ${x.pr_number}`,x.rfq_number&&`RFQ ${x.rfq_number}`].filter(Boolean).join(" • ")});if(x.rfq_number&&String(x.rfq_number).toLowerCase().includes(term.toLowerCase()))hits.push({type:"RFQ",title:x.rfq_number,subtitle:`Linked PO ${x.po_number}`,href:`/purchase-orders/${x.id}`})});
  (ir.data??[]).forEach((x:any)=>hits.push({type:"Invoice",title:x.invoice_number,subtitle:String(x.workflow_status||x.status||"Invoice").replaceAll("_"," "),href:`/invoices/${x.id}`,meta:x.verification_ref||""}));
  (pyr.data??[]).forEach((x:any)=>hits.push({type:"Payment",title:x.payment_reference||x.bank_reference||`Payment ${x.payment_date||""}`,subtitle:`${x.payment_date||""} • ${Number(x.paid_amount||0).toLocaleString()}`,href:`/payments/${x.id}/edit`,meta:x.bank_reference||""}));
  (dr.data??[]).forEach((x:any)=>hits.push({type:"Document",title:x.document_title||x.file_name,subtitle:x.document_type||"Document",href:x.google_drive_web_url||"/documents",meta:x.revision||""}));
  (mr.data??[]).forEach((x:any)=>hits.push({type:"Milestone",title:x.milestone_name,subtitle:`${String(x.status||"").replaceAll("_"," ")} • ${x.payment_due_date||"No due date"}`,href:`/payment-milestones/${x.id}/edit`}));
  const numeric=Number(term.replace(/,/g,""));
  if(Number.isFinite(numeric)&&numeric!==0){const [np,ni,ny]=await Promise.all([s.from("purchase_orders").select("id,po_number,current_value").eq("is_deleted",false).eq("current_value",numeric).limit(20),s.from("invoices").select("id,invoice_number,invoice_amount,certified_amount").eq("is_deleted",false).or(`invoice_amount.eq.${numeric},certified_amount.eq.${numeric}`).limit(20),s.from("payments").select("id,payment_reference,payment_date,paid_amount").eq("paid_amount",numeric).limit(20)]);(np.data??[]).forEach((x:any)=>hits.push({type:"Purchase Order Amount",title:x.po_number,subtitle:`Amount ${Number(x.current_value||0).toLocaleString()}`,href:`/purchase-orders/${x.id}`}));(ni.data??[]).forEach((x:any)=>hits.push({type:"Invoice Amount",title:x.invoice_number,subtitle:`Invoice ${Number(x.invoice_amount||0).toLocaleString()} • Certified ${Number(x.certified_amount||0).toLocaleString()}`,href:`/invoices/${x.id}`}));(ny.data??[]).forEach((x:any)=>hits.push({type:"Payment Amount",title:x.payment_reference||"Payment",subtitle:`${x.payment_date||""} • ${Number(x.paid_amount||0).toLocaleString()}`,href:`/payments/${x.id}/edit`}));}
 }
 return <div className="mx-auto max-w-[1500px]"><div className="text-xs font-extrabold uppercase tracking-[.2em] text-blue-700">Global Search</div><h1 className="mt-2 text-3xl font-bold">Search MCCS</h1><form className="mt-6 flex gap-2"><input name="q" defaultValue={term} autoFocus className="input max-w-3xl" placeholder="Search any PO, RFQ, vendor, invoice, payment, project/package, document..."/><button className="rounded-xl bg-[#07111f] px-5 py-3 text-sm font-bold text-white">Search</button></form>{term?<div className="mt-5 text-sm text-slate-500">{hits.length} result{hits.length===1?"":"s"} for <b>{term}</b></div>:null}<div className="mt-6 grid gap-3">{hits.map((h,i)=><Link key={`${h.type}-${i}-${h.href}`} href={h.href} target={h.href.startsWith("http")?"_blank":undefined} className="mccs-card rounded-2xl p-5 hover:border-blue-300"><div className="flex items-start justify-between gap-4"><div><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700">{h.type}</span><div className="mt-2 text-lg font-bold">{h.title}</div><div className="mt-1 text-sm text-slate-600">{h.subtitle}</div>{h.meta?<div className="mt-1 text-xs text-slate-500">{h.meta}</div>:null}</div><span className="text-sm font-bold text-blue-700">Open →</span></div></Link>)}{term&&!hits.length?<div className="mccs-card rounded-2xl p-10 text-center text-slate-500">No matching commercial record found.</div>:null}</div></div>
}
