"use client";
import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,PieChart,Pie,Cell,Legend,AreaChart,Area,CartesianGrid} from "recharts";

export function DashboardCharts({vendorData,statusData,cashflowData,selectedVendor=""}:{vendorData:any[];statusData:any[];cashflowData:any[];selectedVendor?:string}){
  const router=useRouter();
  const [months,setMonths]=useState<"6"|"12"|"all">("12");
  const [showDue,setShowDue]=useState(true);
  const [showPaid,setShowPaid]=useState(true);
  const [selectedMonth,setSelectedMonth]=useState<string>("");
  const visibleCashflow=useMemo(()=>months==="all"?cashflowData:cashflowData.slice(-Number(months)),[cashflowData,months]);
  const selectedCash=useMemo(()=>visibleCashflow.find((x:any)=>x.month===selectedMonth)||null,[visibleCashflow,selectedMonth]);
  const money=(v:any)=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2});
  const goVendor=(d:any)=>{if(!d?.vendorId)return;router.push(`/dashboard?vendor=${encodeURIComponent(d.vendorId)}`)};
  const goStatus=(d:any)=>{if(!d?.name)return;const p=new URLSearchParams();p.set("status",String(d.name).replaceAll(" ","_"));if(selectedVendor)p.set("vendor",selectedVendor);router.push(`/payment-milestones?${p.toString()}`)};
  return <div className="grid gap-5 xl:grid-cols-2">
    <section className="mccs-card rounded-2xl p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-bold">Commitment by Vendor</h2><p className="mt-1 text-sm text-slate-500">Live commercial commitments. Click a bar to instantly filter the complete dashboard by supplier.</p></div><span className="rounded-lg bg-blue-50 px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wide text-blue-700">Click to filter</span></div><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={vendorData} onClick={(e:any)=>goVendor(e?.activePayload?.[0]?.payload)}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip formatter={(v:any)=>money(v)} cursor={{fill:"rgba(37,99,235,.06)"}}/><Bar dataKey="value" radius={[8,8,0,0]} fill="#2563eb" cursor="pointer"/></BarChart></ResponsiveContainer></div></section>
    <section className="mccs-card rounded-2xl p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-bold">Milestone Status</h2><p className="mt-1 text-sm text-slate-500">Click any segment to open the live payment milestone records for that status.</p></div><a href="/payment-milestones" className="rounded-lg border px-3 py-2 text-xs font-bold text-blue-700 hover:bg-blue-50">Open all</a></div><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={statusData} dataKey="value" nameKey="name" innerRadius={65} outerRadius={100} paddingAngle={3} cursor="pointer" onClick={(d:any)=>goStatus(d)}>{statusData.map((_:any,i:number)=><Cell key={i} fill={["#2563eb","#0f766e","#d97706","#7c3aed","#64748b","#dc2626"][i%6]}/>)}</Pie><Tooltip/><Legend onClick={(e:any)=>{const hit=statusData.find((x:any)=>x.name===e?.value);if(hit)goStatus(hit)}}/></PieChart></ResponsiveContainer></div></section>
    <section className="mccs-card rounded-2xl p-6 xl:col-span-2"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-bold">Commercial Cash Flow</h2><p className="mt-1 text-sm text-slate-500">Interactive monthly milestone due value versus actual payments. Click any month to inspect its values.</p></div><div className="flex flex-wrap items-center gap-2"><div className="flex rounded-lg border bg-white p-1 dark:bg-slate-900">{[["6","6M"],["12","12M"],["all","All"]].map(([v,l])=><button key={v} type="button" onClick={()=>{setMonths(v as any);setSelectedMonth("")}} className={`rounded-md px-3 py-1.5 text-xs font-bold ${months===v?"bg-blue-700 text-white":"text-slate-600 hover:bg-slate-50"}`}>{l}</button>)}</div><button type="button" onClick={()=>setShowDue(x=>!x)} className={`rounded-lg border px-3 py-2 text-xs font-bold ${showDue?"border-blue-200 bg-blue-50 text-blue-700":"text-slate-400"}`}>Milestone Due</button><button type="button" onClick={()=>setShowPaid(x=>!x)} className={`rounded-lg border px-3 py-2 text-xs font-bold ${showPaid?"border-emerald-200 bg-emerald-50 text-emerald-700":"text-slate-400"}`}>Paid</button></div></div>{selectedCash?<div className="mt-4 flex flex-wrap items-center gap-3 rounded-xl border border-blue-100 bg-blue-50/60 px-4 py-3 text-sm dark:border-blue-900/40 dark:bg-blue-950/20"><span className="font-extrabold text-blue-700">{selectedCash.month}</span><span>Milestone Due: <b>{money(selectedCash.due)}</b></span><span>Paid: <b className="text-emerald-700">{money(selectedCash.paid)}</b></span><button className="ml-auto text-xs font-bold text-blue-700" onClick={()=>setSelectedMonth("")}>Clear month</button></div>:null}<div className="mt-5 h-80"><ResponsiveContainer width="100%" height="100%"><AreaChart data={visibleCashflow} onClick={(e:any)=>{const d=e?.activePayload?.[0]?.payload;if(d?.month)setSelectedMonth(String(d.month))}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip formatter={(v:any)=>money(v)}/><Legend/>{showDue?<Area type="monotone" dataKey="due" name="Milestone Due" fill="#bfdbfe" stroke="#2563eb" activeDot={{r:6,cursor:"pointer"}}/>:null}{showPaid?<Area type="monotone" dataKey="paid" name="Paid" fill="#bbf7d0" stroke="#16a34a" activeDot={{r:6,cursor:"pointer"}}/>:null}</AreaChart></ResponsiveContainer></div></section>
  </div>
}
