import Link from "next/link";
import { updatePurchaseOrderDetails } from "../../../_actions/commercial";
import { createClient } from "@/lib/supabase/server";
import { POMilestoneEditor } from "@/components/commercial-linked-forms";

export const dynamic = "force-dynamic";

export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string}>}){
 const {id}=await params,q=await searchParams,s=await createClient();if(!s)return null;
 const [rr,vr,cr,pr,mr]=await Promise.all([
  s.from("purchase_orders").select("*").eq("id",id).maybeSingle(),
  s.from("vendors").select("id,vendor_name,parent_vendor_id").eq("is_active",true).order("vendor_name"),
  s.from("currencies").select("id,code").eq("is_active",true),
  s.from("projects").select("id,project_code,project_name").eq("is_active",true),
  s.from("payment_milestones").select("id,milestone_name,percentage,fixed_amount,planned_due_date,payment_due_date,status,sequence_no").eq("purchase_order_id",id).eq("is_deleted",false).order("sequence_no")
 ]);
 const x=rr.data;if(!x)return <div>PO not found.</div>;
 const currencyCode=(cr.data??[]).find((c:any)=>String(c.id)===String(x.currency_id))?.code||"";
 const milestoneRows=(mr.data??[]).map((m:any)=>({id:String(m.id),milestone_name:String(m.milestone_name||""),percentage:m.percentage==null?null:Number(m.percentage),fixed_amount:m.fixed_amount==null?null:Number(m.fixed_amount),planned_due_date:m.planned_due_date||"",payment_due_date:m.payment_due_date||"",status:m.status||"planned"}));
 return <div className="mx-auto max-w-6xl"><div className="flex justify-between"><div><div className="text-xs font-extrabold uppercase tracking-[.2em] text-blue-700">Commercial Commitment</div><h1 className="mt-2 text-3xl font-bold">Edit PO {x.po_number}</h1><p className="mt-2 text-sm text-slate-500">Edit PO commercial details and maintain its payment milestones in the same screen.</p></div><Link href={`/purchase-orders/${id}`} className="font-bold text-blue-700">Back</Link></div>{q.error?<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{q.error}</div>:null}
 <form action={updatePurchaseOrderDetails} className="mccs-card mt-7 rounded-2xl p-6"><input type="hidden" name="po_id" value={id}/><h2 className="text-lg font-bold">Commercial Information</h2><div className="mt-5 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
 <F l="PO Number *"><input name="po_number" defaultValue={x.po_number} required className="input"/></F><F l="PO Date *"><input name="po_date" type="date" defaultValue={x.po_date} required className="input"/></F><F l="Project / Package"><select name="project_id" defaultValue={x.project_id||""} className="input"><option value="">No project</option>{(pr.data??[]).map((v:any)=><option key={v.id} value={v.id}>{v.project_code} — {v.project_name}</option>)}</select></F><F l="Vendor *"><select name="vendor_id" defaultValue={x.vendor_id} required className="input">{(vr.data??[]).map((v:any)=><option key={v.id} value={v.id}>{v.vendor_name}</option>)}</select></F><F l="Parent Contractor"><select name="parent_contractor_id" defaultValue={x.parent_contractor_id||""} className="input"><option value="">None / Direct</option>{(vr.data??[]).filter((v:any)=>!v.parent_vendor_id).map((v:any)=><option key={v.id} value={v.id}>{v.vendor_name}</option>)}</select></F><F l="Currency *"><select name="currency_id" defaultValue={x.currency_id} required className="input">{(cr.data??[]).map((v:any)=><option key={v.id} value={v.id}>{v.code}</option>)}</select></F><F l="Original PO Value *"><input name="original_value" type="number" step="0.01" defaultValue={x.original_value||0} required className="input"/></F><F l="PR Number"><input name="pr_number" defaultValue={x.pr_number||""} className="input"/></F><F l="RFQ Number"><input name="rfq_number" defaultValue={x.rfq_number||""} className="input"/></F><F l="Prepared By"><input name="prepared_by" defaultValue={x.prepared_by||""} className="input"/></F><F l="Initial PO Date"><input name="initial_po_date" type="date" defaultValue={x.initial_po_date||x.po_date||""} className="input"/></F><F l="Revised PO Date"><input name="revised_po_date" type="date" defaultValue={x.revised_po_date||""} className="input"/></F><F l="Status"><select name="status" defaultValue={x.status||"active"} className="input"><option value="draft">Draft</option><option value="active">Active</option><option value="on_hold">On Hold</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></F></div>
 <POMilestoneEditor initialRows={milestoneRows} currencyCode={currencyCode}/>
 <h2 className="mt-8 text-lg font-bold">PO Print Template Details</h2><div className="mt-5 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><F l="Payment Terms"><textarea name="payment_terms" defaultValue={x.payment_terms||""} rows={3} className="input"/></F><F l="Delivery Terms"><textarea name="delivery_terms" defaultValue={x.delivery_terms||""} rows={3} className="input"/></F><F l="Delivery Due"><input name="delivery_due_date" type="date" defaultValue={x.delivery_due_date||""} className="input"/></F><F l="Incoterm 2020"><input name="incoterm" defaultValue={x.incoterm||""} className="input"/></F><F l="Origin of Goods"><input name="origin_of_goods" defaultValue={x.origin_of_goods||""} className="input"/></F><F l="Warranty"><textarea name="warranty" defaultValue={x.warranty||""} rows={2} className="input"/></F><F l="Quote Ref"><input name="quote_ref" defaultValue={x.quote_ref||""} className="input"/></F><F l="Quote Date"><input name="quote_date" type="date" defaultValue={x.quote_date||""} className="input"/></F><F l="Discount"><input name="discount" type="number" step="0.01" defaultValue={x.discount||0} className="input"/></F><F l="Extra"><input name="extra_cost" type="number" step="0.01" defaultValue={x.extra_cost||0} className="input"/></F><F l="Shipping Address"><textarea name="shipping_address" defaultValue={x.shipping_address||""} rows={3} className="input"/></F><F l="Billing Address"><textarea name="billing_address" defaultValue={x.billing_address||""} rows={3} className="input"/></F><F l="Other Instruction"><textarea name="other_instruction" defaultValue={x.other_instruction||""} rows={4} className="input lg:col-span-3"/></F><F l="Approval Date"><input name="approval_date" type="date" defaultValue={x.approval_date||""} className="input"/></F><F l="Approved By"><input name="approved_by_text" defaultValue={x.approved_by_text||""} className="input"/></F><F l="Historical Source"><input name="historical_source" defaultValue={x.historical_source||""} className="input"/></F></div><label className="mt-5 flex items-center gap-3"><input type="checkbox" name="is_historical" defaultChecked={!!x.is_historical}/> Historical / previously approved PO</label><F l="Notes"><textarea name="notes" defaultValue={x.notes||""} rows={3} className="input mt-5"/></F><div className="mt-7 flex justify-end"><button className="rounded-xl bg-[#07111f] px-5 py-3 text-sm font-bold text-white">Save PO & Milestone Changes</button></div></form></div>
}
function F({l,children}:{l:string;children:React.ReactNode}){return <label><span className="mb-2 block text-sm font-bold text-slate-700 dark:text-slate-200">{l}</span>{children}</label>}
