import ExcelJS from "exceljs";
import { requireSuperAdmin } from "@/lib/mccs/auth";
export const dynamic="force-dynamic";
function style(ws:ExcelJS.Worksheet){ws.views=[{state:"frozen",ySplit:1}];ws.getRow(1).font={bold:true};ws.getRow(1).height=22;ws.columns.forEach(c=>c.width=20);ws.autoFilter={from:{row:1,column:1},to:{row:1,column:ws.columnCount}}}
export async function GET(){await requireSuperAdmin();const wb=new ExcelJS.Workbook();wb.creator="MCCS";wb.created=new Date();
 const defs:[string,string[],any[]][]=[
 ["Vendors",["vendor_code","vendor_name","legal_name","country","address","contact_person","email","phone","notes"],["EMR","Emerson","Emerson Automation Solutions","","","","","",""]],
 ["Projects_Packages",["project_code","project_name","vendor_code","description","start_date","planned_finish_date"],["SUP-PSV","Supply PSV","EMR","PSV supply package","2026-01-01","2026-12-31"]],
 ["Purchase_Orders",["po_number","project_code","vendor_code","po_date","pr_number","rfq_number","currency_code","original_value","status","payment_terms","delivery_terms","delivery_due_date","incoterm","origin_of_goods","warranty","quote_ref","quote_date","prepared_by","discount","extra_cost","historical_source"],["MEL-RA-845026","SUP-PSV","EMR","2026-08-18","MR-EPF-100-IC-RFQ-0039-REV01","MR-EPF-100-IC-RFQ-0039-REV01","IQD",22995750,"active","25% Advance with PO, remaining 75% after delivery","75 Days After Accepting the Purchasing Order & Receiving Advanced Payment","2026-11-01","DDP-Miran Site","Switzerland","12 months from operation or 18 months after delivery","OFE4351556","2026-08-17","Rawa Amanj",1023000,0,"Legacy register"]],
 ["Milestones",["po_number","milestone_name","sequence_no","percentage","fixed_amount","planned_due_date","payment_due_date","status","discipline"],["MEL-RA-845026","Advance Payment",1,25,"","2026-08-20","2026-08-20","planned","Commercial"]],
 ["Invoices",["invoice_number","po_number","invoice_date","received_date","currency_code","invoice_amount","certified_amount","status","workflow_status","due_date","historical_source"],["INV-EXAMPLE","MEL-RA-845026","2026-08-20","2026-08-20","IQD",5748937.5,5748937.5,"received","received","2026-09-20","Legacy register"]],
 ["Payments",["payment_reference","po_number","invoice_number","currency_code","payment_date","paid_amount","bank_reference","historical_source"],["PAY-EXAMPLE","MEL-RA-845026","INV-EXAMPLE","IQD","2026-08-25",5748937.5,"BANK-REF","Legacy register"]]
 ];for(const [name,headers,sample] of defs){const ws=wb.addWorksheet(name);ws.addRow(headers);ws.addRow(sample);style(ws)}
 const b=await wb.xlsx.writeBuffer();return new Response(b as any,{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":"attachment; filename=\"MCCS-Historical-Import-Template.xlsx\""}})}
