import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { importHistoricalWorkbook } from "../../_actions/commercial";
export const dynamic="force-dynamic";
export default async function Page({searchParams}:{searchParams:Promise<{error?:string;success?:string;summary?:string}>}){
 const q=await searchParams; const s=await createClient(); if(!s) redirect("/login"); const {data:{user}}=await s.auth.getUser(); if(!user) redirect("/login"); const {data:me}=await s.from("profiles").select("is_super_admin").eq("id",user.id).maybeSingle(); if(!me?.is_super_admin && user.email?.toLowerCase()!=="sarwar.khalid@miranenergy.com") redirect("/dashboard"); let summary:any=null;try{summary=q.summary?JSON.parse(q.summary):null}catch{}
 return <div className="mx-auto max-w-5xl"><div className="flex items-end justify-between"><div><div className="text-xs font-extrabold uppercase tracking-[.2em] text-blue-700">Super Admin • Go-Live</div><h1 className="mt-2 text-3xl font-bold">Historical Data Import</h1><p className="mt-2 text-sm text-slate-500">Load approved historical commercial data so MCCS can go live mid-project without losing the earlier project history.</p></div><Link href="/admin" className="font-bold text-blue-700">Back</Link></div>
 {q.error?<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{q.error}</div>:null}
 {q.success?<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800"><b>Import completed.</b>{summary?<div className="mt-2 grid gap-2 text-sm md:grid-cols-3">{Object.entries(summary).map(([k,v])=><div key={k} className="rounded-lg bg-white/60 px-3 py-2"><b className="capitalize">{k}</b>: {String(v)}</div>)}</div>:null}</div>:null}
 <div className="mccs-card mt-7 rounded-2xl p-6"><h2 className="text-lg font-bold">1. Download the controlled import template</h2><p className="mt-2 text-sm text-slate-500">The workbook contains separate sheets for Vendors, Projects/Packages, Purchase Orders, Milestones, Invoices and Payments. Keep the header names unchanged.</p><a href="/api/admin/historical-import/template" className="mt-4 inline-flex rounded-xl border bg-white px-4 py-3 text-sm font-bold text-blue-700">Download Historical Import Template.xlsx</a></div>
 <form action={importHistoricalWorkbook} className="mccs-card mt-5 rounded-2xl p-6"><h2 className="text-lg font-bold">2. Upload completed workbook</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><label><span className="mb-2 block text-sm font-bold">Historical workbook *</span><input type="file" name="historical_workbook" required accept=".xlsx" className="input"/></label><label><span className="mb-2 block text-sm font-bold">Historical source / cut-off reference</span><input name="historical_source" className="input" placeholder="e.g. Legacy register cut-off 23-Aug-2026"/></label></div><div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Controlled import:</b> existing records with the same commercial keys are updated; new records are added and flagged as historical. Physical historical documents should still be uploaded through Documents so they are stored in Google Drive.</div><button className="mt-5 rounded-xl bg-[#07111f] px-5 py-3 text-sm font-bold text-white">Import Historical Data</button></form>
 </div>
}
