import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import SuperAdminDelete from "@/components/super-admin-delete";
import { deletePaymentMilestone } from "../_actions/commercial";
export const dynamic="force-dynamic";
export default async function Page({searchParams}:{searchParams:Promise<{deleted?:string;error?:string}>}){
 const q=await searchParams,supabase=await createClient();if(!supabase)return null;const {data:{user}}=await supabase.auth.getUser();const {data:me}=user?await supabase.from("profiles").select("is_super_admin").eq("id",user.id).maybeSingle():{data:null as any};const isSuperAdmin=Boolean(me?.is_super_admin||user?.email?.toLowerCase()==="sarwar.khalid@miranenergy.com");
 const mr=await supabase.from("payment_milestones").select("id,purchase_order_id,milestone_name,percentage,fixed_amount,planned_due_date,payment_due_date,status,is_deleted").eq("is_deleted",false).order("planned_due_date");const rows=mr.data??[];const poIds=[...new Set(rows.map((r:any)=>r.purchase_order_id))];const pr=poIds.length?await supabase.from("purchase_orders").select("id,po_number,current_value,currency_id").in("id",poIds).eq("is_deleted",false):{data:[]} as any;const pos=new Map<string,any>((pr.data??[]).map((p:any)=>[String(p.id),p]));const cids=[...new Set((pr.data??[]).map((p:any)=>p.currency_id).filter(Boolean))];const cr=cids.length?await supabase.from("currencies").select("id,code").in("id",cids):{data:[]} as any;const currencies=new Map<string,string>((cr.data??[]).map((c:any)=>[String(c.id),String(c.code??"")]));
 const summaryMap=new Map<string,{po_number:string;allocated:number;remaining:number;remainingAmount:number}>();for(const m of rows){const p=pos.get(String((m as any).purchase_order_id));if(!p)continue;const k=String(p.id),cur=summaryMap.get(k)||{po_number:p.po_number,allocated:0,remaining:100,remainingAmount:Number(p.current_value||0)};const pct=(m as any).percentage!=null?Number((m as any).percentage):Number(p.current_value||0)?Number((m as any).fixed_amount||0)/Number(p.current_value||0)*100:0;cur.allocated+=pct;cur.remaining=Math.max(0,100-cur.allocated);cur.remainingAmount=Math.max(0,Number(p.current_value||0)*(cur.remaining/100));summaryMap.set(k,cur)}
 return <div className="mx-auto max-w-[1600px]">{q.deleted?<div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">Milestone deleted. PO allocation has been recalculated from active milestones.</div>:null}{q.error?<div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{q.error}</div>:null}<div className="text-xs font-extrabold uppercase tracking-[0.2em] text-blue-700">MCCS</div><h1 className="mt-2 text-3xl font-bold">Payment Milestones</h1><p className="mt-2 text-sm text-slate-500">Contractual payment obligations, allocation and remaining PO exposure.</p>
 <div className="mt-6 grid gap-4 md:grid-cols-3">{[...summaryMap.entries()].slice(0,6).map(([id,s])=>{const p=pos.get(id);return <div key={id} className="mccs-card rounded-2xl p-5"><div className="text-xs font-bold uppercase text-slate-500">{s.po_number}</div><div className="mt-2 text-2xl font-bold">{s.allocated.toFixed(2)}% allocated</div><div className="mt-2 text-sm text-slate-500">Remaining: {s.remaining.toFixed(2)}% • {currencies.get(p?.currency_id)||""} {s.remainingAmount.toLocaleString()}</div></div>})}</div>
 <div className="mccs-card mt-6 overflow-hidden rounded-2xl"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">PO</th><th className="px-5 py-3">Milestone</th><th className="px-5 py-3">%</th><th className="px-5 py-3">Calculated Amount</th><th className="px-5 py-3">Due</th><th className="px-5 py-3">Payment Due</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Actions</th></tr></thead><tbody className="divide-y">{rows.map((m:any)=>{const p=pos.get(String(m.purchase_order_id));const amt=m.percentage!=null?Number(p?.current_value||0)*Number(m.percentage)/100:Number(m.fixed_amount||0);return <tr key={m.id}><td className="px-5 py-4 font-bold">{p?.po_number||"—"}</td><td className="px-5 py-4">{m.milestone_name}</td><td className="px-5 py-4 font-semibold">{m.percentage!=null?`${Number(m.percentage).toFixed(2)}%`:"—"}</td><td className="px-5 py-4">{currencies.get(p?.currency_id)||""} {amt.toLocaleString()}</td><td className="px-5 py-4">{m.planned_due_date||"—"}</td><td className="px-5 py-4">{m.payment_due_date||"—"}</td><td className="px-5 py-4 capitalize">{m.status}</td><td className="px-5 py-4"><div className="flex gap-3"><Link href={`/payment-milestones/${m.id}/edit`} className="font-bold text-blue-700">Edit</Link>{isSuperAdmin?<SuperAdminDelete entity="milestone" entityId={m.id} entityLabel={m.milestone_name} idField="milestone_id" action={deletePaymentMilestone}/>:null}</div></td></tr>})}{!rows.length?<tr><td colSpan={8} className="px-5 py-12 text-center text-slate-500">No payment milestones yet.</td></tr>:null}</tbody></table></div></div>;
}
