"use client";
import { useMemo, useState } from "react";
import { useFormStatus } from "react-dom";
import Link from "next/link";
import { createPurchaseOrder } from "../../_actions/commercial";
export function POForm({vendors,currencies,projects,error}:{vendors:any[];currencies:any[];projects:any[];error?:string}){
 const [poValue,setPoValue]=useState(0);const [vendorId,setVendorId]=useState("");const [milestones,setMilestones]=useState([{name:"",percentage:"",amount:"",due:"",paymentDue:"",discipline:""}]);
 const add=()=>setMilestones([...milestones,{name:"",percentage:"",amount:"",due:"",paymentDue:"",discipline:""}]);const remove=(i:number)=>setMilestones(milestones.filter((_,x)=>x!==i));const update=(i:number,k:string,v:string)=>setMilestones(milestones.map((m,x)=>x===i?{...m,[k]:v}:m));
 const allocatedPct=useMemo(()=>milestones.reduce((s,m)=>s+(Number(m.percentage)||0),0),[milestones]);const allocatedAmount=useMemo(()=>milestones.reduce((s,m)=>s+(m.percentage!==""?poValue*(Number(m.percentage)||0)/100:(Number(m.amount.replace(/,/g,""))||0)),0),[milestones,poValue]);
 return <form action={createPurchaseOrder} className="mccs-card mt-7 rounded-2xl p-6">{error?<div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>:null}
 <h2 className="text-lg font-bold">Commercial Information</h2><div className="mt-5 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
 <F l="PO Number *"><input name="po_number" required className="input"/></F><F l="PO Date *"><input name="po_date" type="date" required className="input"/></F><F l="Vendor / Contractor *"><select name="vendor_id" required className="input" value={vendorId} onChange={e=>setVendorId(e.target.value)}><option value="">Select vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.vendor_name}</option>)}</select></F>
 <F l="Parent Contractor"><select name="parent_contractor_id" className="input"><option value="">None / Direct</option>{vendors.filter(v=>!v.parent_vendor_id).map(v=><option key={v.id} value={v.id}>{v.vendor_name}</option>)}</select></F><F l="Commercial Project / Package *"><select name="project_id" required className="input"><option value="">Select project / package</option>{projects.filter(p=>!vendorId||String(p.vendor_id)===vendorId).map(p=><option key={p.id} value={p.id}>{p.project_name} ({p.project_code})</option>)}</select></F><F l="Currency *"><select name="currency_id" required className="input"><option value="">Select currency</option>{currencies.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></F><F l="Original PO Value *"><input name="original_value" required inputMode="decimal" className="input" onChange={e=>setPoValue(Number(e.target.value.replace(/,/g,""))||0)}/></F>
 <F l="PR Number"><input name="pr_number" className="input"/></F><F l="RFQ Number"><input name="rfq_number" className="input"/></F><F l="Approval Date"><input name="approval_date" type="date" className="input"/></F><F l="Approved By"><input name="approved_by_text" className="input"/></F><F l="Prepared By"><input name="prepared_by" className="input"/></F><F l="Initial PO Date"><input name="initial_po_date" type="date" className="input"/></F><F l="Revised PO Date"><input name="revised_po_date" type="date" className="input"/></F><F l="Status"><select name="status" className="input"><option value="active">Active</option><option value="draft">Draft</option><option value="completed">Completed</option><option value="closed">Closed</option></select></F></div>
 <h2 className="mt-8 text-lg font-bold">Miran PO Print Template Details</h2><p className="mt-1 text-sm text-slate-500">These fields feed the controlled three-page PDF based on the approved Miran PO format.</p><div className="mt-5 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
 <F l="Payment Terms"><textarea name="payment_terms" rows={3} className="input"/></F><F l="Delivery Terms"><textarea name="delivery_terms" rows={3} className="input"/></F><F l="Delivery Due Date"><input name="delivery_due_date" type="date" className="input"/></F><F l="Incoterm 2020"><input name="incoterm" className="input" placeholder="DDP-Miran Site"/></F><F l="Origin of Goods"><input name="origin_of_goods" className="input"/></F><F l="Warranty"><textarea name="warranty" rows={2} className="input"/></F><F l="Quote Ref"><input name="quote_ref" className="input"/></F><F l="Quote Date"><input name="quote_date" type="date" className="input"/></F><F l="Discount"><input name="discount" inputMode="decimal" defaultValue="0" className="input"/></F><F l="Extra"><input name="extra_cost" inputMode="decimal" defaultValue="0" className="input"/></F><F l="Shipping Address"><textarea name="shipping_address" rows={3} className="input" placeholder="Miran Energy LTD ..."/></F><F l="Billing Address"><textarea name="billing_address" rows={3} className="input" placeholder="TAURUS ARM Co. ..."/></F><F l="Other Instruction"><textarea name="other_instruction" rows={3} className="input lg:col-span-3"/></F></div>
 <div className="mt-8 rounded-2xl border p-5"><h2 className="text-lg font-bold">First PO Item</h2><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><F l="Item Code"><input name="item_code" className="input"/></F><F l="Site"><input name="item_site" defaultValue="MEL" className="input"/></F><F l="UOM"><input name="item_uom" defaultValue="Each" className="input"/></F><F l="Quantity"><input name="item_quantity" defaultValue="1" inputMode="decimal" className="input"/></F><F l="Item / Description"><textarea name="item_description" rows={4} className="input lg:col-span-3"/></F><F l="Unit Cost"><input name="item_unit_cost" inputMode="decimal" className="input"/></F></div><p className="mt-2 text-xs text-slate-500">More items can be added from the PO detail page after creation.</p></div>
 <div className="mt-8 rounded-2xl border border-slate-200 bg-slate-50 p-5"><h2 className="text-lg font-bold">PO Supporting Documents</h2><p className="mt-1 text-sm text-slate-500">Stored under Vendor → Project/Package → PO → PO Number.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><F l="Purchase Order PDF"><input name="po_pdf" type="file" accept=".pdf" className="input"/></F><F l="Technical Offer"><input name="technical_offer" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.zip,image/*" className="input"/></F><F l="Supporting Documents (multiple)"><input name="supporting_files" type="file" multiple accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.zip,image/*" className="input"/></F></div></div>
 <div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><label className="font-bold text-amber-900"><input type="checkbox" name="is_historical" className="mr-2"/>Historical / approved before MCCS</label><input name="historical_source" className="input mt-3" placeholder="Evidence/source reference"/></div>
 <div className="mt-8 flex items-end justify-between"><div><h2 className="text-lg font-bold">Payment Milestones</h2><p className="text-sm text-slate-500">Percentage automatically calculates milestone amount from the PO value.</p></div><button type="button" onClick={add} className="rounded-xl border bg-white px-4 py-2 text-sm font-bold">+ Add Milestone</button></div><input type="hidden" name="milestone_count" value={milestones.length}/>
 <div className="mt-4 grid gap-3 md:grid-cols-3"><Summary l="Allocated" v={`${allocatedPct.toFixed(2)}%`} sub={allocatedAmount.toLocaleString()}/><Summary l="Remaining" v={`${Math.max(100-allocatedPct,0).toFixed(2)}%`} sub={Math.max(poValue-allocatedAmount,0).toLocaleString()}/><Summary l="PO Value" v={poValue.toLocaleString()} sub="Current commitment"/></div>
 <div className="mt-4 space-y-3">{milestones.map((m,i)=><div key={i} className="rounded-2xl border bg-slate-50 p-4"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-6"><input name={`milestone_name_${i}`} value={m.name} onChange={e=>update(i,"name",e.target.value)} className="input lg:col-span-2" placeholder="Milestone name"/><input name={`milestone_percentage_${i}`} value={m.percentage} onChange={e=>update(i,"percentage",e.target.value)} className="input" placeholder="%"/><input name={`milestone_amount_${i}`} value={m.amount} onChange={e=>update(i,"amount",e.target.value)} className="input" placeholder="Fixed amount"/><input name={`milestone_due_${i}`} value={m.due} onChange={e=>update(i,"due",e.target.value)} type="date" className="input"/><input name={`milestone_payment_due_${i}`} value={m.paymentDue} onChange={e=>update(i,"paymentDue",e.target.value)} type="date" className="input"/><input name={`milestone_discipline_${i}`} value={m.discipline} onChange={e=>update(i,"discipline",e.target.value)} className="input lg:col-span-2" placeholder="Discipline / verifier"/>{milestones.length>1?<button type="button" onClick={()=>remove(i)} className="text-left text-sm font-bold text-red-600">Remove</button>:null}</div></div>)}</div>
 <div className="mt-7 flex justify-end gap-3"><Link href="/purchase-orders" className="rounded-xl border px-5 py-3 text-sm font-bold">Cancel</Link><CreatePOSubmitButton allocationInvalid={allocatedPct>100}/></div></form>
}
function CreatePOSubmitButton({allocationInvalid}:{allocationInvalid:boolean}){const {pending}=useFormStatus();return <button disabled={allocationInvalid||pending} className="rounded-xl bg-[#07111f] px-5 py-3 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">{pending?"Creating PO…":"Create PO, Milestones & Folder"}</button>}
function F({l,children}:{l:string;children:React.ReactNode}){return <label><span className="mb-2 block text-sm font-bold text-slate-700">{l}</span>{children}</label>}
function Summary({l,v,sub}:{l:string;v:string;sub:string}){return <div className="rounded-2xl border bg-white p-4"><div className="text-xs font-bold uppercase text-slate-500">{l}</div><div className="mt-1 text-xl font-bold">{v}</div><div className="text-xs text-slate-500">{sub}</div></div>}
