"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import {
  CheckCheck, ChevronDown, FileText, Link2, MessageCircle, Mic, MicOff, MoreVertical,
  Paperclip, Pause, Phone, Play, Search, Send, Share2, Square, UserRound, X
} from "lucide-react";
import { getWebRtcIceServers, uploadChatVoice } from "../_actions/commercial";

type ChatUser={id:string;full_name?:string|null;preferred_name?:string|null;avatar_url?:string|null;last_seen_at?:string|null};
type ChatDocument={id:string;document_title?:string|null;file_name?:string|null;document_type?:string|null;vendor_id?:string|null;vendor_name?:string|null};
type ChatMessage={id:string;sender_id:string;recipient_id:string;body:string;created_at:string;read_at?:string|null;attachment_document_id?:string|null;message_type?:string|null;voice_duration_seconds?:number|null;voice_waveform?:number[]|null};
type ChatCall={id:string;caller_id:string;receiver_id:string;status:string;call_type:string;started_at?:string|null;ringing_at?:string|null;answered_at?:string|null;ended_at?:string|null;duration_seconds?:number|null;screen_shared?:boolean;created_at?:string|null};
type Signal={id:number;call_id:string;sender_id:string;recipient_id:string;signal_type:string;payload:any;created_at:string};

const PAGE_SIZE=50;
function name(u?:ChatUser|null){return u?.preferred_name?.trim()||u?.full_name?.trim()||"MCCS User"}
function initials(u?:ChatUser|null){const p=name(u).split(/\s+/);return `${p[0]?.[0]||"U"}${p[1]?.[0]||p[0]?.[1]||""}`.toUpperCase()}
function fmtTime(v?:string|null){if(!v)return"";const d=new Date(v);return d.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}
function fmtDate(v?:string|null){if(!v)return"";return new Date(v).toLocaleString([],{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"})}
function durationLabel(s?:number|null){const n=Math.max(0,Math.round(Number(s||0)));return `${Math.floor(n/60)}:${String(n%60).padStart(2,"0")}`}
function bars(v?:number[]|null){return Array.isArray(v)&&v.length?v.slice(0,46):Array.from({length:34},(_,i)=>.18+((i*13)%8)/12)}

export default function MessagesPage(){
  const supabase=useMemo(()=>createClient(),[]);
  const [me,setMe]=useState(""); const [users,setUsers]=useState<ChatUser[]>([]); const [online,setOnline]=useState<Set<string>>(new Set());
  const [selectedId,setSelectedId]=useState(""); const [messages,setMessages]=useState<ChatMessage[]>([]); const [hasOlder,setHasOlder]=useState(false); const [loadingOlder,setLoadingOlder]=useState(false);
  const [documents,setDocuments]=useState<ChatDocument[]>([]); const [attachment,setAttachment]=useState(""); const [text,setText]=useState(""); const [query,setQuery]=useState(""); const [error,setError]=useState("");
  const [detailTab,setDetailTab]=useState<"details"|"files"|"calls">("details"); const [newBelow,setNewBelow]=useState(false);
  const scrollRef=useRef<HTMLDivElement>(null); const bottomRef=useRef<HTMLDivElement>(null); const oldestRef=useRef("");
  const selected=users.find(u=>u.id===selectedId)||null; const docMap=useMemo(()=>new Map(documents.map(d=>[d.id,d])),[documents]);

  // Voice message recording.
  const [recording,setRecording]=useState(false); const [recSec,setRecSec]=useState(0); const [wave,setWave]=useState<number[]>([]); const waveRef=useRef<number[]>([]);
  const [preview,setPreview]=useState<{blob:Blob;url:string;duration:number;waveform:number[]}|null>(null); const recRef=useRef<MediaRecorder|null>(null); const chunks=useRef<Blob[]>([]); const streamRef=useRef<MediaStream|null>(null); const recStarted=useRef(0); const timerRef=useRef<number|null>(null);

  // WebRTC voice call + screen sharing.
  const [incoming,setIncoming]=useState<ChatCall|null>(null); const [call,setCall]=useState<ChatCall|null>(null); const [callStatus,setCallStatus]=useState(""); const [muted,setMuted]=useState(false); const [sharing,setSharing]=useState(false); const [callSeconds,setCallSeconds]=useState(0);
  const pcRef=useRef<RTCPeerConnection|null>(null); const micRef=useRef<MediaStream|null>(null); const screenRef=useRef<MediaStream|null>(null); const remoteAudio=useRef<HTMLAudioElement>(null); const remoteVideo=useRef<HTMLVideoElement>(null); const callPartnerRef=useRef(""); const activeCallIdRef=useRef(""); const callStartRef=useRef<number>(0); const callTimer=useRef<number|null>(null);

  const pairFilter=useCallback((partner:string)=>`and(sender_id.eq.${me},recipient_id.eq.${partner}),and(sender_id.eq.${partner},recipient_id.eq.${me})`,[me]);

  const loadLatest=useCallback(async(partner:string)=>{
    if(!me||!partner)return; setError("");
    const {data,error:e}=await supabase.from("chat_messages").select("id,sender_id,recipient_id,body,created_at,read_at,attachment_document_id,message_type,voice_duration_seconds,voice_waveform").or(pairFilter(partner)).order("created_at",{ascending:false}).limit(PAGE_SIZE+1);
    if(e){setError(e.message);return} const rows=(data||[]) as ChatMessage[]; setHasOlder(rows.length>PAGE_SIZE); const page=rows.slice(0,PAGE_SIZE).reverse(); setMessages(page); oldestRef.current=page[0]?.created_at||"";
    await supabase.from("chat_messages").update({read_at:new Date().toISOString()}).eq("sender_id",partner).eq("recipient_id",me).is("read_at",null);
    requestAnimationFrame(()=>bottomRef.current?.scrollIntoView({behavior:"auto"}));
  },[me,pairFilter,supabase]);

  async function loadOlder(){
    if(!selectedId||!hasOlder||loadingOlder||!oldestRef.current)return; const box=scrollRef.current;if(!box)return; setLoadingOlder(true); const oldHeight=box.scrollHeight;
    const {data,error:e}=await supabase.from("chat_messages").select("id,sender_id,recipient_id,body,created_at,read_at,attachment_document_id,message_type,voice_duration_seconds,voice_waveform").or(pairFilter(selectedId)).lt("created_at",oldestRef.current).order("created_at",{ascending:false}).limit(PAGE_SIZE+1);
    if(!e){const rows=(data||[]) as ChatMessage[];setHasOlder(rows.length>PAGE_SIZE);const page=rows.slice(0,PAGE_SIZE).reverse();setMessages(m=>[...page,...m]);oldestRef.current=page[0]?.created_at||oldestRef.current;requestAnimationFrame(()=>{box.scrollTop=box.scrollHeight-oldHeight+box.scrollTop})} setLoadingOlder(false);
  }

  useEffect(()=>{let alive=true;void(async()=>{const {data}=await supabase.auth.getUser();const uid=data.user?.id||"";if(!uid)return;if(!alive)return;setMe(uid);
    const [{data:profiles},{data:docs},{data:vendors}]=await Promise.all([
      supabase.from("profiles").select("id,full_name,preferred_name,avatar_url,last_seen_at").neq("id",uid).order("full_name"),
      supabase.from("documents").select("id,document_title,file_name,document_type,vendor_id").eq("is_deleted",false).neq("document_category","chat_voice").order("uploaded_at",{ascending:false}).limit(200),
      supabase.from("vendors").select("id,vendor_name")
    ]);
    const vm=new Map((vendors||[]).map((v:any)=>[String(v.id),String(v.vendor_name||"")]));setDocuments(((docs||[]) as any[]).map(d=>({...d,vendor_name:vm.get(String(d.vendor_id||""))||"Unassigned Supplier"})));const list=(profiles||[]) as ChatUser[];setUsers(list);const qs=new URLSearchParams(location.search).get("user");setSelectedId(qs||list[0]?.id||"");})();return()=>{alive=false}},[supabase]);

  // True Supabase Realtime Presence directory.
  useEffect(()=>{if(!me)return;const ch=supabase.channel("mccs-user-presence",{config:{presence:{key:me}}});
    const sync=()=>{const state=ch.presenceState() as Record<string,any[]>;setOnline(new Set(Object.keys(state)))};ch.on("presence",{event:"sync"},sync).on("presence",{event:"join"},sync).on("presence",{event:"leave"},sync).subscribe(async status=>{if(status==="SUBSCRIBED")await ch.track({user_id:me,online_at:new Date().toISOString()})});return()=>{void ch.untrack();void supabase.removeChannel(ch)}},[me,supabase]);

  useEffect(()=>{if(selectedId&&me)void loadLatest(selectedId)},[selectedId,me,loadLatest]);

  // Message realtime. Voice calling is owned by the global authenticated MCCS layout so calls persist across navigation.
  useEffect(()=>{if(!me)return;const ch=supabase.channel(`mccs-messages-${me}`)
    .on("postgres_changes",{event:"INSERT",schema:"public",table:"chat_messages"},(p:any)=>{const m=p.new as ChatMessage;if(m.sender_id!==me&&m.recipient_id!==me)return;const belongs=selectedId&&((m.sender_id===me&&m.recipient_id===selectedId)||(m.sender_id===selectedId&&m.recipient_id===me));if(!belongs)return;setMessages(x=>x.some(y=>y.id===m.id)?x:[...x,m]);const box=scrollRef.current;const atBottom=!box||box.scrollHeight-box.scrollTop-box.clientHeight<120;if(atBottom)requestAnimationFrame(()=>bottomRef.current?.scrollIntoView({behavior:"smooth"}));else setNewBelow(true)})
    .subscribe();return()=>{void supabase.removeChannel(ch)}},[me,selectedId,supabase]);

  function setCallPartner(id:string){callPartnerRef.current=id;setSelectedId(id)}
  async function sendSignal(callId:string,recipient:string,type:string,payload:any){await supabase.from("chat_call_signals").insert({call_id:callId,sender_id:me,recipient_id:recipient,signal_type:type,payload})}
  async function createPeer(callId:string,partner:string){
    if(pcRef.current)return pcRef.current;const iceServers=await getWebRtcIceServers();const pc=new RTCPeerConnection({iceServers});pcRef.current=pc;activeCallIdRef.current=callId;callPartnerRef.current=partner;
    pc.onicecandidate=e=>{if(e.candidate)void sendSignal(callId,partner,"ice",e.candidate.toJSON())};
    pc.ontrack=e=>{const stream=e.streams[0];if(e.track.kind==="audio"&&remoteAudio.current){remoteAudio.current.srcObject=stream;void remoteAudio.current.play().catch(()=>{})}if(e.track.kind==="video"&&remoteVideo.current){remoteVideo.current.srcObject=stream;setSharing(true)}};
    pc.onconnectionstatechange=()=>{const s=pc.connectionState;if(s==="connected"){setCallStatus("Connected");startCallTimer()}else if(["disconnected","connecting"].includes(s))setCallStatus("Reconnecting...");else if(s==="failed")void endCall("failed")};
    return pc;
  }
  async function ensureMic(){if(micRef.current)return micRef.current;try{const s=await navigator.mediaDevices.getUserMedia({audio:true,video:false});micRef.current=s;return s}catch{throw new Error("Microphone access is required for voice calling.")}}
  async function prepareLocal(pc:RTCPeerConnection){const s=await ensureMic();for(const t of s.getAudioTracks())if(!pc.getSenders().some(x=>x.track?.id===t.id))pc.addTrack(t,s)}
  async function handleSignal(sig:Signal){if(!sig?.call_id)return;const cId=sig.call_id;const partner=sig.sender_id;if(sig.signal_type==="hangup"){cleanupCall("ended",false);return}if(sig.signal_type==="screen-start")setSharing(true);if(sig.signal_type==="screen-stop")setSharing(false);
    if(sig.signal_type==="offer"){if(!activeCallIdRef.current||activeCallIdRef.current!==cId)return;const pc=await createPeer(cId,partner);await prepareLocal(pc);await pc.setRemoteDescription(new RTCSessionDescription(sig.payload));const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await sendSignal(cId,partner,"answer",ans);return}
    if(activeCallIdRef.current!==cId||!pcRef.current)return;const pc=pcRef.current;if(sig.signal_type==="answer"){await pc.setRemoteDescription(new RTCSessionDescription(sig.payload))}else if(sig.signal_type==="ice"){try{await pc.addIceCandidate(new RTCIceCandidate(sig.payload))}catch{}}
  }
  function startCallTimer(){if(callTimer.current)return;callStartRef.current=Date.now();callTimer.current=window.setInterval(()=>setCallSeconds(Math.floor((Date.now()-callStartRef.current)/1000)),1000)}
  async function initiateCall(){
    if(!selectedId)return;
    window.dispatchEvent(new CustomEvent("mccs:start-voice-call",{detail:{userId:selectedId}}));
  }
  async function acceptCall(){const c=incoming;if(!c)return;setIncoming(null);setCall(c);activeCallIdRef.current=c.id;callPartnerRef.current=c.caller_id;setCallStatus("Connecting…");try{const pc=await createPeer(c.id,c.caller_id);await prepareLocal(pc);const {data:sigs}=await supabase.from("chat_call_signals").select("*").eq("call_id",c.id).eq("recipient_id",me).eq("signal_type","offer").order("created_at",{ascending:false}).limit(1);const offer=(sigs?.[0] as Signal|undefined)?.payload;if(!offer)throw new Error("Call invitation is missing its WebRTC offer.");await pc.setRemoteDescription(new RTCSessionDescription(offer));const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await sendSignal(c.id,c.caller_id,"answer",ans);await supabase.from("chat_calls").update({status:"connected",answered_at:new Date().toISOString(),started_at:new Date().toISOString()}).eq("id",c.id);setCallStatus("Connected");startCallTimer()}catch(e:any){setError(e?.message||"Unable to accept call.");void endCall("failed")}}
  async function declineCall(){const c=incoming;if(!c)return;await supabase.from("chat_calls").update({status:"declined",ended_at:new Date().toISOString(),ended_by:me}).eq("id",c.id);setIncoming(null)}
  async function endCall(status="ended"){const id=activeCallIdRef.current;if(!id){cleanupCall(status,false);return}const partner=callPartnerRef.current;try{if(partner)await sendSignal(id,partner,"hangup",{});await supabase.from("chat_calls").update({status,ended_at:new Date().toISOString(),duration_seconds:callSeconds,ended_by:me,screen_shared:sharing}).eq("id",id);if(partner)await supabase.from("chat_messages").insert({sender_id:me,recipient_id:partner,body:`📞 Voice call${sharing?" · Screen shared":""} · ${durationLabel(callSeconds)}`,message_type:"call"})}finally{cleanupCall(status,false)}}
  function cleanupCall(status:string,clearDb:boolean){pcRef.current?.close();pcRef.current=null;micRef.current?.getTracks().forEach(t=>t.stop());micRef.current=null;screenRef.current?.getTracks().forEach(t=>t.stop());screenRef.current=null;if(callTimer.current)window.clearInterval(callTimer.current);callTimer.current=null;activeCallIdRef.current="";callPartnerRef.current="";setCall(null);setCallStatus(status);setMuted(false);setSharing(false);setCallSeconds(0);if(remoteAudio.current)remoteAudio.current.srcObject=null;if(remoteVideo.current)remoteVideo.current.srcObject=null}
  function toggleMute(){const track=micRef.current?.getAudioTracks()[0];if(!track)return;track.enabled=!track.enabled;setMuted(!track.enabled)}
  async function startShare(){if(!pcRef.current||!activeCallIdRef.current)return;try{const s=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});screenRef.current=s;const track=s.getVideoTracks()[0];pcRef.current.addTrack(track,s);setSharing(true);await supabase.from("chat_calls").update({screen_shared:true}).eq("id",activeCallIdRef.current);await sendSignal(activeCallIdRef.current,callPartnerRef.current,"screen-start",{});track.onended=()=>void stopShare();const offer=await pcRef.current.createOffer();await pcRef.current.setLocalDescription(offer);await sendSignal(activeCallIdRef.current,callPartnerRef.current,"offer",offer)}catch{setError("Screen sharing was cancelled.")}}
  async function stopShare(){const s=screenRef.current;if(!s)return;for(const t of s.getTracks()){const sender=pcRef.current?.getSenders().find(x=>x.track===t);if(sender)pcRef.current?.removeTrack(sender);t.stop()}screenRef.current=null;setSharing(false);if(activeCallIdRef.current){await supabase.from("chat_calls").update({screen_shared:false}).eq("id",activeCallIdRef.current);await sendSignal(activeCallIdRef.current,callPartnerRef.current,"screen-stop",{});if(pcRef.current){const offer=await pcRef.current.createOffer();await pcRef.current.setLocalDescription(offer);await sendSignal(activeCallIdRef.current,callPartnerRef.current,"offer",offer)}}}

  async function sendMessage(){const body=text.trim();if(!me||!selectedId||(!body&&!attachment))return;const {data,error:e}=await supabase.from("chat_messages").insert({sender_id:me,recipient_id:selectedId,body,attachment_document_id:attachment||null,message_type:"text"}).select("*").single();if(e){setError(e.message);return}setText("");setAttachment("");if(data)setMessages(x=>x.some(m=>m.id===data.id)?x:[...x,data as ChatMessage]);requestAnimationFrame(()=>bottomRef.current?.scrollIntoView({behavior:"smooth"}))}

  async function startRecording(){if(recording)return;setError("");setPreview(null);setWave([]);waveRef.current=[];try{const s=await navigator.mediaDevices.getUserMedia({audio:true,video:false});streamRef.current=s;const mime=MediaRecorder.isTypeSupported("audio/webm;codecs=opus")?"audio/webm;codecs=opus":"audio/webm";const r=new MediaRecorder(s,{mimeType:mime});recRef.current=r;chunks.current=[];recStarted.current=Date.now();r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=()=>{const dur=Math.max(1,Math.round((Date.now()-recStarted.current)/1000));const blob=new Blob(chunks.current,{type:r.mimeType});if(blob.size)setPreview({blob,url:URL.createObjectURL(blob),duration:dur,waveform:waveRef.current.length?waveRef.current:bars()});setRecording(false);streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(timerRef.current)window.clearInterval(timerRef.current)};r.start(250);setRecording(true);timerRef.current=window.setInterval(()=>{const sec=Math.floor((Date.now()-recStarted.current)/1000);setRecSec(sec);const sample=.16+((Date.now()/110)%8)/11;waveRef.current=[...waveRef.current.slice(-45),Math.min(1,sample)];setWave(waveRef.current)},120)}catch{setError("Microphone access is required to record a voice message.")}}
  function stopRecording(){if(recRef.current?.state==="recording")recRef.current.stop()}
  function cancelRecording(){if(recRef.current?.state==="recording"){recRef.current.onstop=null;recRef.current.stop()}streamRef.current?.getTracks().forEach(t=>t.stop());setRecording(false);setPreview(null);setRecSec(0);setWave([])}
  async function sendVoice(){if(!preview||!selectedId)return;const fd=new FormData();fd.append("recipient_id",selectedId);fd.append("duration_seconds",String(preview.duration));fd.append("waveform",JSON.stringify(preview.waveform));fd.append("voice",new File([preview.blob],`voice-${Date.now()}.webm`,{type:preview.blob.type||"audio/webm"}));try{const m=await uploadChatVoice(fd) as ChatMessage;setMessages(x=>[...x,m]);URL.revokeObjectURL(preview.url);setPreview(null)}catch(e:any){setError(e?.message||"Voice message could not be sent.")}}

  const filtered=users.filter(u=>name(u).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(online.has(b.id))-Number(online.has(a.id))||name(a).localeCompare(name(b)));
  return <div className="mx-auto max-w-[1680px]">
    <div className="mb-4"><div className="text-[10px] font-black uppercase tracking-[.2em] text-blue-600">Collaboration</div><h1 className="text-3xl font-black text-slate-950 dark:text-white">Messages</h1><p className="text-sm text-slate-500">Private MCCS chat, Google Drive attachments, voice messages and secure WebRTC voice calls.</p></div>
    {error?<div className="mb-3 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{error}</div>:null}
    <div className="grid h-[calc(100vh-185px)] min-h-[650px] grid-cols-[320px_minmax(0,1fr)_320px] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-950">
      <aside className="border-r border-slate-200 p-3 dark:border-slate-800"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search users..." className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-9 pr-3 text-sm dark:border-slate-700 dark:bg-slate-900"/></div><div className="mt-3 text-[10px] font-black uppercase tracking-[.16em] text-slate-400">Online & conversations</div><div className="mt-2 space-y-1 overflow-y-auto pr-1" style={{maxHeight:"calc(100vh - 300px)"}}>{filtered.map(u=><button key={u.id} onClick={()=>setSelectedId(u.id)} className={`flex w-full items-center gap-3 rounded-xl p-3 text-left transition ${selectedId===u.id?"bg-blue-50 ring-1 ring-blue-100 dark:bg-blue-950/40":"hover:bg-slate-50 dark:hover:bg-slate-900"}`}><div className="relative h-11 w-11 shrink-0 overflow-hidden rounded-full bg-slate-100 text-center text-sm font-black leading-[44px] dark:bg-slate-800">{u.avatar_url?<img src={u.avatar_url} className="h-full w-full object-cover" alt=""/>:initials(u)}<span className={`absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-white ${online.has(u.id)?"bg-emerald-500":"bg-slate-300"}`}/></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-extrabold text-slate-900 dark:text-slate-100">{name(u)}</div><div className={`text-xs ${online.has(u.id)?"font-bold text-emerald-600":"text-slate-400"}`}>{online.has(u.id)?"Online":u.last_seen_at?`Last seen ${fmtDate(u.last_seen_at)}`:"Offline"}</div></div></button>)}</div></aside>

      <section className="flex min-w-0 flex-col"><div className="flex h-[72px] items-center justify-between border-b border-slate-200 px-5 dark:border-slate-800"><div className="flex items-center gap-3"><div className="relative h-11 w-11 overflow-hidden rounded-full bg-slate-100 text-center font-black leading-[44px] dark:bg-slate-800">{selected?.avatar_url?<img src={selected.avatar_url} className="h-full w-full object-cover" alt=""/>:initials(selected)}<span className={`absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-white ${selected&&online.has(selected.id)?"bg-emerald-500":"bg-slate-300"}`}/></div><div><div className="font-black text-slate-950 dark:text-white">{name(selected)}</div><div className={`text-xs ${selected&&online.has(selected.id)?"font-bold text-emerald-600":"text-slate-400"}`}>{selected&&online.has(selected.id)?"Online":selected?.last_seen_at?`Last seen ${fmtDate(selected.last_seen_at)}`:"Offline"}</div></div></div><div className="flex items-center gap-2"><button onClick={()=>void initiateCall()} disabled={!selectedId||!!call} className="rounded-xl border border-slate-200 p-2.5 text-blue-600 hover:bg-blue-50 disabled:opacity-40 dark:border-slate-700" title="Voice Call"><Phone className="h-5 w-5"/></button><button className="rounded-xl border border-slate-200 p-2.5 text-slate-500 dark:border-slate-700" title="More"><MoreVertical className="h-5 w-5"/></button></div></div>

        <div ref={scrollRef} onScroll={e=>{const el=e.currentTarget;if(el.scrollTop<80)void loadOlder();if(el.scrollHeight-el.scrollTop-el.clientHeight<90)setNewBelow(false)}} className="relative flex-1 overflow-y-auto bg-[radial-gradient(circle_at_1px_1px,rgba(148,163,184,.08)_1px,transparent_0)] bg-[length:18px_18px] p-5 dark:bg-slate-950">{loadingOlder?<div className="mb-3 text-center text-xs font-bold text-slate-400">Loading earlier messages…</div>:null}{!hasOlder&&messages.length?<div className="mb-4 text-center text-[10px] font-bold uppercase tracking-[.15em] text-slate-400">Beginning of conversation</div>:null}{messages.map(m=>{const mine=m.sender_id===me;const doc=m.attachment_document_id?docMap.get(m.attachment_document_id):null;const voice=m.message_type==="voice";return <div key={m.id} className={`mb-3 flex ${mine?"justify-end":"justify-start"}`}><div className={`max-w-[72%] rounded-2xl px-4 py-3 text-sm shadow-sm ${mine?"bg-blue-600 text-white":"border border-slate-200 bg-white text-slate-800 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100"}`}>{m.body?<div>{m.body}</div>:null}{doc?<a href={`/api/documents/${doc.id}/file`} target="_blank" className={`mt-2 flex items-center gap-2 rounded-xl border p-2.5 ${mine?"border-white/20 bg-white/10":"border-slate-200 bg-slate-50 dark:border-slate-700 dark:bg-slate-800"}`}><FileText className="h-5 w-5"/><span className="min-w-0"><span className="block truncate font-bold">{doc.document_title||doc.file_name}</span><span className={`block text-[11px] ${mine?"text-blue-100":"text-slate-500"}`}>{doc.vendor_name||"Unassigned Supplier"}</span></span></a>:null}{voice&&m.attachment_document_id?<div className="mt-1 flex items-center gap-2"><audio controls preload="none" src={`/api/documents/${m.attachment_document_id}/file`} className="h-9 max-w-[270px]"/><span className="text-xs">{durationLabel(m.voice_duration_seconds)}</span></div>:null}<div className={`mt-1 flex items-center justify-end gap-1 text-[10px] ${mine?"text-blue-100":"text-slate-400"}`}>{fmtTime(m.created_at)}{mine?<CheckCheck className="h-3 w-3"/>:null}</div></div></div>})}<div ref={bottomRef}/>{newBelow?<button onClick={()=>bottomRef.current?.scrollIntoView({behavior:"smooth"})} className="sticky bottom-2 mx-auto flex items-center gap-1 rounded-full bg-slate-900 px-3 py-1.5 text-xs font-bold text-white shadow-lg"><ChevronDown className="h-4 w-4"/>New Messages</button>:null}</div>

        <div className="border-t border-slate-200 p-3 dark:border-slate-800"><div className="mb-2 flex items-center gap-2"><Paperclip className="h-4 w-4 text-slate-400"/><select value={attachment} onChange={e=>setAttachment(e.target.value)} className="max-w-[520px] rounded-lg border border-slate-200 bg-white px-2 py-1.5 text-xs dark:border-slate-700 dark:bg-slate-900"><option value="">Attach an existing MCCS / Google Drive document</option>{documents.map(d=><option key={d.id} value={d.id}>{d.vendor_name} — {d.document_title||d.file_name}</option>)}</select></div>
          {recording?<div className="mb-2 flex items-center gap-3 rounded-xl border border-rose-200 bg-rose-50 p-3"><Mic className="h-5 w-5 text-rose-600"/><span className="font-bold text-rose-700">{durationLabel(recSec)}</span><div className="flex flex-1 items-center gap-[2px]">{bars(wave).map((v,i)=><span key={i} className="w-[2px] rounded bg-rose-400" style={{height:`${8+v*22}px`}}/>)}</div><button onClick={cancelRecording} className="rounded-lg px-3 py-2 text-sm font-bold">Cancel</button><button onClick={stopRecording} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white"><Square className="h-4 w-4"/></button></div>:null}
          {preview?<div className="mb-2 flex items-center gap-3 rounded-xl border border-blue-200 bg-blue-50 p-3"><audio controls src={preview.url} className="h-9 flex-1"/><button onClick={()=>{URL.revokeObjectURL(preview.url);setPreview(null)}} className="rounded-lg px-3 py-2 text-sm font-bold">Delete</button><button onClick={()=>void sendVoice()} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white">Send</button></div>:null}
          <div className="flex items-end gap-2"><button className="flex h-11 w-11 items-center justify-center rounded-xl border border-slate-200 dark:border-slate-700"><Paperclip className="h-4 w-4"/></button><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void sendMessage()}}} placeholder="Type a message..." rows={1} className="min-h-11 flex-1 resize-none rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm dark:border-slate-700 dark:bg-slate-900"/><button onClick={()=>void startRecording()} className="flex h-11 w-11 items-center justify-center rounded-xl border border-blue-200 text-blue-600 hover:bg-blue-50" title="Record voice message"><Mic className="h-5 w-5"/></button><button onClick={()=>void sendMessage()} className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-600 text-white"><Send className="h-5 w-5"/></button></div></div>
      </section>

      <aside className="border-l border-slate-200 p-4 dark:border-slate-800"><div className="flex border-b border-slate-200 dark:border-slate-800">{(["details","files","calls"] as const).map(t=><button key={t} onClick={()=>setDetailTab(t)} className={`flex-1 border-b-2 px-2 py-3 text-xs font-extrabold capitalize ${detailTab===t?"border-blue-600 text-blue-600":"border-transparent text-slate-500"}`}>{t}</button>)}</div>{detailTab==="details"?<div className="pt-6 text-center"><div className="mx-auto h-24 w-24 overflow-hidden rounded-full bg-slate-100 text-2xl font-black leading-[96px] dark:bg-slate-800">{selected?.avatar_url?<img src={selected.avatar_url} className="h-full w-full object-cover" alt=""/>:initials(selected)}</div><div className="mt-3 text-lg font-black">{name(selected)}</div><div className={`mt-1 text-xs font-bold ${selected&&online.has(selected.id)?"text-emerald-600":"text-slate-400"}`}>{selected&&online.has(selected.id)?"● Online":selected?.last_seen_at?`Last seen ${fmtDate(selected.last_seen_at)}`:"Offline"}</div><button onClick={()=>void initiateCall()} className="mx-auto mt-6 flex items-center gap-2 rounded-xl border border-blue-200 px-4 py-3 text-sm font-bold text-blue-600"><Phone className="h-4 w-4"/>Voice Call</button><p className="mt-4 text-xs leading-5 text-slate-500">Voice calls use browser WebRTC. Screen sharing is available only after the voice call connects. No webcam is requested.</p></div>:detailTab==="files"?<div className="pt-4 space-y-2">{messages.filter(m=>m.attachment_document_id).slice(-20).reverse().map(m=>{const d=docMap.get(m.attachment_document_id!);return d?<a key={m.id} href={`/api/documents/${d.id}/file`} target="_blank" className="block rounded-xl border border-slate-200 p-3 text-xs dark:border-slate-700"><b className="block truncate">{d.document_title||d.file_name}</b><span className="text-slate-500">{d.vendor_name}</span></a>:null})}</div>:<div className="pt-4 text-sm text-slate-500">Call events are shown in the conversation when a call ends.</div>}</aside>
    </div>

    {false&&incoming?<div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-950/40 backdrop-blur-sm"><div className="w-[380px] rounded-3xl bg-white p-6 text-center shadow-2xl dark:bg-slate-900"><div className="text-[10px] font-black uppercase tracking-[.18em] text-blue-600">Incoming Voice Call</div><div className="mx-auto mt-5 h-20 w-20 rounded-full bg-slate-100 text-xl font-black leading-[80px] dark:bg-slate-800">{initials(users.find(u=>u.id===incoming.caller_id))}</div><div className="mt-3 text-xl font-black">{name(users.find(u=>u.id===incoming.caller_id))}</div><div className="mt-1 text-sm text-slate-500">MCCS secure WebRTC voice call</div><div className="mt-6 flex gap-3"><button onClick={()=>void declineCall()} className="flex-1 rounded-xl bg-rose-50 px-4 py-3 font-bold text-rose-700">Decline</button><button onClick={()=>void acceptCall()} className="flex-1 rounded-xl bg-emerald-600 px-4 py-3 font-bold text-white">Accept</button></div></div></div>:null}
    {false&&call?<div className="fixed bottom-6 right-6 z-[115] w-[420px] overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-2xl dark:border-slate-700 dark:bg-slate-950"><div className="bg-slate-950 p-5 text-white"><div className="flex items-center justify-between"><div><div className="text-xs font-bold text-blue-300">Voice Call</div><div className="text-lg font-black">{name(users.find(u=>u.id===callPartnerRef.current))}</div><div className="text-xs text-slate-300">{callStatus} · {durationLabel(callSeconds)}</div></div><Phone className="h-7 w-7 text-blue-400"/></div></div>{sharing?<div className="relative bg-black"><video ref={remoteVideo} autoPlay playsInline className="max-h-[240px] w-full object-contain"/><div className="absolute left-3 top-3 rounded-full bg-emerald-500 px-2.5 py-1 text-[10px] font-black text-white">SCREEN SHARING</div></div>:null}<audio ref={remoteAudio} autoPlay/><div className="grid grid-cols-3 gap-2 p-4"><button onClick={toggleMute} className="rounded-xl border border-slate-200 p-3 text-xs font-bold dark:border-slate-700">{muted?<MicOff className="mx-auto mb-1 h-5 w-5"/>:<Mic className="mx-auto mb-1 h-5 w-5"/>}{muted?"Unmute":"Mute"}</button><button onClick={()=>void(sharing?stopShare():startShare())} className="rounded-xl border border-slate-200 p-3 text-xs font-bold dark:border-slate-700"><Share2 className="mx-auto mb-1 h-5 w-5"/>{sharing?"Stop Sharing":"Share Screen"}</button><button onClick={()=>void endCall("ended")} className="rounded-xl bg-rose-600 p-3 text-xs font-bold text-white"><Phone className="mx-auto mb-1 h-5 w-5 rotate-[135deg]"/>End Call</button></div></div>:null}
  </div>
}
